version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: db_example
      MYSQL_USER: user
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - db_network

volumes:
  db_data:

networks:
  db_network: